type GUIModuleType* = enum
    mtAutospinsSwitcher
    mtFullscreenButton
    mtBalloonFreeSpins
    mtBuildingsStoreButton
    mtCandyBonusRules
    mtEiffelBonusRules
    mtMenuButton
    mtMoneyPanel
    mtPayTableOpenButton
    mtPlayerInfo
    mtProfileInfo
    mtSelectAvatar
    mtQuestsButton
    mtQuestWindow
    mtSpinButton
    mtTotalBetPanel
    mtTotalWinPanelBig
    mtTotalWinPanelSmall
    mtWinPanel
    mtExchangePopup
    mtSoundSettings
    mtStorePopup
    mtRewardsPopup
    mtLevelUp
    mtRemoveBuild
    mtSpeedUpBuild
    mtUpgradeBuild
    mtOutOfCurrency
    mtNotAvailableSpots
    mtTutorial
    mtSelectSlot
    mtSelectExchange
    mtBuildingStore
    mtPaytable
    mtPlayButton
    mtMermaidRulesModule
    mtMermaidCounterModule
    mtMapBottomMenu
    mtSidePanel
    mtBoostersPanel
    mtCollectButton
    mtTournamentsButton
    mtSlotBottomMenu
    mtNone
